language: java
jdk:
  - openjdk17
services:
  - postgresql
before_script:
  - psql -c 'create database urimed;' -U postgres
before_install:
  - cd backend/urimed
  - chmod +x mvnw
script: 
  ./mvnw clean install
