language: java
jdk:
  - openjdk17
services:
  - postgresql
before_script:
  - psql -c 'create database urimed;' -U postgres
before_install:
  - cd backend/urimed
  - chmod +x mvnw
after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
script: 
  ./mvnw clean install
