language: java
jdk:
  - openjdk17
services:
  - postgresql
before_script:
  - psql -c 'create database urimed;' -U postgres
before_install:
  - cd backend/urimed
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
script: 
  ./mvnw clean install
