version: '3.8'
services:
  backend:
    build:
      context: ./backend/urimed
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/urimed
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: urimed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: